-- migrate:up
INSERT INTO model (name, formula, description, parameters)
VALUES
('Sips', 'qe = qms * ks * ce**(1/ns) / (1 + (ks * ce**(1/ns)))', 'El modelo de isoterma de Sips es otra ecuación de tres parámetros que combina los desarrollos de Freundlich y Langmuir. En este caso, el modelo fue propuesto para describir sistemas en los que la distribución energética de los sitios activos es heterogénea, pero buscando eludir las limitaciones que presenta el desarrollo de Freundlich cuando se trabaja a una concentración muy elevada.', '{"qms": "es un parámetro que representa la máxima cantidad de adsorción, aquella a la cual el sólido se satura.", "ks": "es la constante de equilibrio", "ns": "es la inversa del exponente, en analogía con modelo de Freundlich"}'),
('Temkin', 'qe = ((R * T)/btk) * log(ktk * ce)', 'El modelo de isoterma de Temins un modelo de dos parámetros que parte del supuesto de que la distribución energética de los sitios de adsorción es uniforme hasta alcanzar un valor máximo, a similitud del modelo de Langmuir. Asume que el calor de adsorción disminuye linealmente a medida que la superficie se va cubriendo, y contiene un coeficiente (factor KTk) que especialmente tiene en cuenta las interacciones adsorbente-adsorbato.', '{"btk": "parámetro que está directamente relacionado con el calor de adsorción.", "ktk": "constante de equilibrio de adsorción del modelo."}'),
('Toth', 'qe = (qm * ce)/((kt + (ce ** tn)) ** (1/tn))','La isoterma de Toth comprende una ecuación semi-empírica desarrollada con el objeto de mejorar la aplicabilidad del modelo de Langmuir. Dicho desarrollo se llevó a cabo buscando reducir la diferencia entre los valores observados experimentalmente durante un proceso de adsorción y los valores predichos por la isoterma','{"qm":"es un parámetro que representa la máxima cantidad de adsorción", "kt":"es la constante de equilibrio", "tn":"es un parámetro capaz de dar indicio sobre el grado de heterogeneidad que presenta el material adsorbente."}')


-- migrate:down

