services:
  database:
    image: postgres:13
    restart: always
    container_name: adsolab_postgre_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=adsolab
    ports:
      - '5432:5432'
    volumes:
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
  dbmate:
    image: "ghcr.io/amacneil/dbmate:1"
    container_name: db_migrations_adsolab
    volumes:
      - "./db:/db"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@database:5432/adsolab?sslmode=disable
    depends_on:
      - "database"
    command: "--wait up"

#  pgadmin:
#    container_name: pgadmin
#    image: dpage/pgadmin4
#    environment:
#      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
#      - PGADMIN_DEFAULT_PASSWORD=admin
#    ports:
#      - "9999:80"
#    depends_on:
#      - postgres

#  pedidos_rapidos:
#    image: pedidos_rapidos
#    build:
#      context: .
#    environment:
#      - PORT=80
#      - DATABASE_URL=postgresql://postgres:postgres@postgres/pedidos_rapidos
#    ports:
#      - 8080:80
#    volumes:
#      - ./pedidos_rapidos:/opt/app/pedidos_rapidos
#      - ./tests:/opt/app/tests
#
#    # skip alembic migration
#    #entrypoint: 'sh -c "sleep 10 && poetry run uvicorn pedidos_rapidos.main:app --port $$PORT --host 0.0.0.0 --debug"'
#    # run alemic migration
#    entrypoint: 'sh -c "sleep 10 && poetry run alembic upgrade head && poetry run uvicorn pedidos_rapidos.main:app --port $$PORT --host 0.0.0.0 --debug"'
#    depends_on:
#      - postgres
