name: Release (dev)

on:
  push:
    branches:
      - main
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - run: sudo curl -fsSL -o /usr/local/bin/dbmate https://github.com/amacneil/dbmate/releases/latest/download/dbmate-linux-amd64
    - run: sudo chmod +x /usr/local/bin/dbmate
    - run: |
        PGPASSWORD=${{secrets.DB_PASSWORD_DEV}} psql -h ${{secrets.DB_URL_DEV}} -U ${{secrets.DB_USERNAME_DEV}} -d adsolab -c "
        DO \$\$
        DECLARE
          r RECORD;
        BEGIN
          FOR r IN (SELECT tablename FROM pg_tables WHERE schemaname = current_schema()) LOOP
            EXECUTE 'DROP TABLE IF EXISTS ' || quote_ident(r.tablename) || ' CASCADE';
          END LOOP;
        END \$\$;"
    - run: dbmate -u 'postgresql://${{secrets.DB_USERNAME_DEV}}:${{secrets.DB_PASSWORD_DEV}}@${{secrets.DB_URL_DEV}}/adsolab?sslmode=require' up
