name: Release (dev)

on:
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - run: sudo curl -fsSL -o /usr/local/bin/dbmate https://github.com/amacneil/dbmate/releases/latest/download/dbmate-linux-amd64
    - run: sudo chmod +x /usr/local/bin/dbmate
    - run: dbmate -u 'postgresql://${{secrets.DB_USERNAME_DEV}}:${{secrets.DB_PASSWORD_DEV}}@${{secrets.DB_URL_DEV}}/adsolab?sslmode=disable' status
